export const SALA_LIST_REQUEST = 'SALA_LIST_REQUEST';
export const SALA_LIST_SUCCESS = 'SALA_LIST_SUCCESS';
export const SALA_LIST_FAIL = 'SALA_LIST_FAIL';

export const SALA_DETAILS_REQUEST = 'SALA_DETAILS_REQUEST';
export const SALA_DETAILS_SUCCESS = 'SALA_DETAILS_SUCCESS';
export const SALA_DETAILS_FAIL = 'SALA_DETAILS_FAIL';

export const SALA_DELETE_REQUEST = 'SALA_DELETE_REQUEST';
export const SALA_DELETE_SUCCESS = 'SALA_DELETE_SUCCESS';
export const SALA_DELETE_FAIL = 'SALA_DELETE_FAIL';

export const SALA_CREATE_REQUEST = 'SALA_CREATE_REQUEST';
export const SALA_CREATE_SUCCESS = 'SALA_CREATE_SUCCESS';
export const SALA_CREATE_FAIL = 'SALA_CREATE_FAIL';
export const SALA_CREATE_RESET = 'SALA_CREATE_RESET';

export const SALA_UPDATE_REQUEST = 'SALA_UPDATE_REQUEST';
export const SALA_UPDATE_SUCCESS = 'SALA_UPDATE_SUCCESS';
export const SALA_UPDATE_FAIL = 'SALA_UPDATE_FAIL';
export const SALA_UPDATE_RESET = 'SALA_UPDATE_RESET';

export const SALA_CREATE_REVIEW_REQUEST = 'SALA_CREATE_REVIEW_REQUEST';
export const SALA_CREATE_REVIEW_SUCCESS = 'SALA_CREATE_REVIEW_SUCCESS';
export const SALA_CREATE_REVIEW_FAIL = 'SALA_CREATE_REVIEW_FAIL';
export const SALA_CREATE_REVIEW_RESET = 'SALA_CREATE_REVIEW_RESET';

export const SALA_TOP_REQUEST = 'SALA_TOP_REQUEST';
export const SALA_TOP_SUCCESS = 'SALA_TOP_SUCCESS';
export const SALA_TOP_FAIL = 'SALA_TOP_FAIL';
