export const SALA_VIEW_REQUEST = 'SALA_VIEW_REQUEST';
export const SALA_VIEW_SUCCESS = 'SALA_VIEW_SUCCESS';
export const SALA_VIEW_FAIL = 'SALA_VIEW_FAIL';
export const SALA_VIEW_RESET = 'SALA_VIEW_RESET';

export const SALA_DETAILS_REQUEST = 'SALA_DETAILS_REQUEST';
export const SALA_DETAILS_SUCCESS = 'SALA_DETAILS_SUCCESS';
export const SALA_DETAILS_FAIL = 'SALA_DETAILS_FAIL';
