export const ESTUDIANTE_LIST_REQUEST = 'ESTUDIANTE_LIST_REQUEST';
export const ESTUDIANTE_LIST_SUCCESS = 'ESTUDIANTE_LIST_SUCCESS';
export const ESTUDIANTE_LIST_FAIL = 'ESTUDIANTE_LIST_FAIL';

export const ESTUDIANTE_DETAILS_REQUEST = 'ESTUDIANTE_DETAILS_REQUEST';
export const ESTUDIANTE_DETAILS_SUCCESS = 'ESTUDIANTE_DETAILS_SUCCESS';
export const ESTUDIANTE_DETAILS_FAIL = 'ESTUDIANTE_DETAILS_FAIL';

export const ESTUDIANTE_DELETE_REQUEST = 'ESTUDIANTE_DELETE_REQUEST';
export const ESTUDIANTE_DELETE_SUCCESS = 'ESTUDIANTE_DELETE_SUCCESS';
export const ESTUDIANTE_DELETE_FAIL = 'ESTUDIANTE_DELETE_FAIL';

export const ESTUDIANTE_CREATE_REQUEST = 'ESTUDIANTE_CREATE_REQUEST';
export const ESTUDIANTE_CREATE_SUCCESS = 'ESTUDIANTE_CREATE_SUCCESS';
export const ESTUDIANTE_CREATE_FAIL = 'ESTUDIANTE_CREATE_FAIL';
export const ESTUDIANTE_CREATE_RESET = 'ESTUDIANTE_CREATE_RESET';

export const ESTUDIANTE_UPDATE_REQUEST = 'ESTUDIANTE_UPDATE_REQUEST';
export const ESTUDIANTE_UPDATE_SUCCESS = 'ESTUDIANTE_UPDATE_SUCCESS';
export const ESTUDIANTE_UPDATE_FAIL = 'ESTUDIANTE_UPDATE_FAIL';
export const ESTUDIANTE_UPDATE_RESET = 'ESTUDIANTE_UPDATE_RESET';
