export const LLAVERO_CREATE_REQUEST = 'LLAVERO_CREATE_REQUEST';
export const LLAVERO_CREATE_SUCCESS = 'LLAVERO_CREATE_SUCCESS';
export const LLAVERO_CREATE_FAIL = 'LLAVERO_CREATE_FAIL';
export const LLAVERO_CREATE_RESET = 'LLAVERO_CREATE_RESET';
