export const LLAVERO_CREATE_REQUEST = 'LLAVERO_CREATE_REQUEST';
export const LLAVERO_CREATE_SUCCESS = 'LLAVERO_CREATE_SUCCESS';
export const LLAVERO_CREATE_FAIL = 'LLAVERO_CREATE_FAIL';
export const LLAVERO_CREATE_RESET = 'LLAVERO_CREATE_RESET';

export const LLAVERO_DETAILS_REQUEST = 'LLAVERO_DETAILS_REQUEST';
export const LLAVERO_DETAILS_SUCCESS = 'LLAVERO_DETAILS_SUCCESS';
export const LLAVERO_DETAILS_FAIL = 'LLAVERO_DETAILS_FAIL';
